Перламутровые пуговицы
htmlacademy-javascript/1864601-keksobooking-24 pull request #12
Opened 2021-11-05 15:52 UTC by LionS7S7S7

2021-11-06 08:09 UTC, what1s1ove requested changes
уже несколько раз писал, удали папку `js/utils`

2021-11-06 08:09 UTC, what1s1ove commented on js/api.js
> +        throw new Error(['Ошибка запроса, не удалось отправить данные']);
зачем массив?
```suggestion
        throw new Error('Ошибка запроса, не удалось отправить данные');
```

2021-11-06 08:09 UTC, what1s1ove commented on js/filter.js
> +  newData = filterFeatures(newData, conditionerFilterElement.value, conditionerFilterElement);
сложновато и не расширяемо в дальнейшем

Подумай над чем-то таким

```js
const featuresFieldsetNode = filterNode.querySelector('#housing-features');

  const checkFeatures = (ad) => {
    const hasFeatures = Boolean(ad.offer.features);
    if (!hasFeatures) {
      return true;
    }
    const checkedFeatures = featuresFieldsetNode.querySelectorAll('input:checked');
    return Array.from(checkedFeatures).every((checkbox) => ad.offer.features.includes(checkbox.value));
  },
```

2021-11-06 08:09 UTC, what1s1ove commented on js/main.js
> +    window.PINS_DATA = serverData;
в финдов мы ничего не запихиваем

2021-11-06 08:09 UTC, what1s1ove commented on js/filter.js
> +  if (typeFilterElement.value !== 'any') {
добавь конcтанту на any
```js
const CONTROL_DEFAULT_VALUE = 'any';
```

2021-11-06 10:07 UTC, LionS7S7S7 commented on js/api.js
> +        throw new Error(['Ошибка запроса, не удалось отправить данные']);
папка utils пришла с новым обновлением от кекса, думал так и надо... окей удалю

2021-11-11 07:32 UTC, what1s1ove requested changes

2021-11-11 07:32 UTC, what1s1ove commented on js/api.js
> +        throw new Error(['Ошибка запроса, не удалось отправить данные']);
Но так и не удалил

2021-11-11 07:32 UTC, what1s1ove commented
Нету никаких изменений

2021-11-14 06:54 UTC, what1s1ove requested changes
**ПОФИКСИ** линтер

2021-11-14 06:54 UTC, what1s1ove commented on js/filter.js
> +  for (let i = 0; i < filterItems.length; i++)
используй forEach

2021-11-14 06:54 UTC, what1s1ove commented on js/filter.js
> +    for (let i = 0; i < filterByFeatures.length; i++)
используй forEach

2021-11-14 06:54 UTC, what1s1ove commented on js/filter.js
> +  for (const key in filterByItems)
используй forEach

2021-11-14 17:39 UTC, what1s1ove approved these changes

2021-11-14 17:39 UTC, merged