Создана функция, возвращающая случайное число. Main.js подключён к in…
htmlacademy-javascript/1864601-keksobooking-24 pull request #3
Opened 2021-09-27 21:08 UTC by LionS7S7S7

Создана функция, возвращающая случайное число. Main.js подключён к index.html

2021-09-28 05:08 UTC, what1s1ove requested changes
нужно написать две функции. посмотри в заданию на первую задачу 👍

2021-09-28 05:08 UTC, what1s1ove commented on index.html
> +  <script src="/Users/aryey/Desktop/Development/Projects/1864601-keksobooking-24/js/main.js"></script>
```suggestion
  <script src="./js/main.js"></script>
```
нужно указывать относительный путь от файла

2021-09-28 05:08 UTC, what1s1ove commented on js/main.js
> +    const DEGREE = 10 ** fractions;
большими буквами просто так ничего писать не нужно)

2021-09-28 19:01 UTC, LionS7S7S7 commented
Изменил название константы на нижний регистр, но возник вопрос, в каких случаях тогда применяется критерий Б7?
(Названия констант (постоянных значений) написаны прописными (заглавными) буквами.)

2021-09-29 04:40 UTC, what1s1ove requested changes

2021-09-29 04:40 UTC, what1s1ove commented on js/main.js
> +    return ('Укажите корректный диапазон для генератора!');
Тут лучше будет кинуть ошибку `throw new Error('Укажите корректный диапазон для генератора!')`

2021-09-29 04:40 UTC, what1s1ove commented on js/main.js
> +      return ('Укажите корректный диапазон для генератора!');
и тут бы тоже ошибку)

2021-09-29 04:40 UTC, merged